statics: "/" # //cdn.jsdelivr.net/gh/BergahornKlen/BergahornKlen.github.io@latest/
assets: "assets" # å›¾ç‰‡èµ„æºå­˜æ”¾ç›®å½•
css: "css" # csså­˜æ”¾ç›®å½•(ä¸å»ºè®®æ”¹åŠ¨)
js: "js" # jså­˜æ”¾ç›®å½•(ä¸å»ºè®®æ”¹åŠ¨)

alternate: "Sycamore"

menu:
  home: / || home
  about:
    default: /about/ || user
    aboutsite: /about/ || cloud
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  friends: /friends/ || heart
  travellings: https://www.travellings.cn || subway

social:
  github: https://github.com/noneSycamore || github || "#191717"

# bgm
audio:
  - title: é“ƒèŠ½ä¹‹æ—…
    list:
    - https://music.163.com/#/playlist?id=8379150105
  - title: English
    list:
    - https://music.163.com/#/playlist?id=8379011186

footer:
  since: 2021

waline:
  enable: true
  serverURL: "https://vercel.sycamore.top"
  lang: "zh-CN"
  locale: {
      placeholder: "1. æé—®å‰è¯·å…ˆä»”ç»†é˜…è¯»æœ¬æ–‡æ¡£âš¡\n2. é¡µé¢æ˜¾ç¤ºé—®é¢˜ğŸ’¥ï¼Œè¯·æä¾›æ§åˆ¶å°æˆªå›¾ğŸ“¸æˆ–è€…æ‚¨çš„æµ‹è¯•ç½‘å€\n3. å…¶ä»–ä»»ä½•æŠ¥é”™ğŸ’£ï¼Œè¯·æä¾›è¯¦ç»†æè¿°å’Œæˆªå›¾ğŸ“¸ï¼Œç¥é£Ÿç”¨æ„‰å¿«ğŸ’ª"
  }
  emoji: # è¡¨æƒ…åŒ…ï¼Œé»˜è®¤ä¸ºwalineå®˜æ–¹é…ç½®
    - https://unpkg.com/@waline/emojis@1.0.1/weibo
    - https://unpkg.com/@waline/emojis@1.0.1/alus
    - https://unpkg.com/@waline/emojis@1.0.1/bilibili
    - https://unpkg.com/@waline/emojis@1.0.1/qq
    - https://unpkg.com/@waline/emojis@1.0.1/tieba
    - https://unpkg.com/@waline/emojis@1.0.1/tw-emoji
  meta: # è¯„è®ºå¯ä»¥å¡«å†™çš„é¡¹ç›®
    - nick
    - mail
    - link
  requiredMeta: # è¯„è®ºå¿…é¡»å¡«å†™çš„é¡¹ç›®
    - nick
    - mail
  wordLimit: 1000 # è¯„è®ºå­—æ•°ä¸Šé™(ä¸å»ºè®®ä¸º0)
  pageSize: 10 # æ¯é¡µæ˜¾ç¤ºè¯„è®ºæ¡æ•°
  pageview: true # é¡µé¢æµè§ˆé‡æ˜¾ç¤º
